config/routes.rb
Rails.application.routes.draw do
  get 'home',        to: "pages#home"
  get 'projects',    to: "pages#projects"
  get 'contact',     to: "pages#contact"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def projects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portafolio Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "layouts/navbars/navbars_principal" %>
  
    <div class="container" >
      <%= yield %>    
    </div>







    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/navbars/_navbars_principal.html.erb
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
      <div class="container-fluid">
        <%# <a class="navbar-brand" href="#">Portafolio</a> %>
        <%= link_to "Portafolio", root_path, class:"text-decoration" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%= link_to "Home", home_path, class:"nav-link active" %>
            <%= link_to "Projects", projects_path, class:"nav-link" %>
            <%= link_to "Contact", contact_path, class:"nav-link" %>
          </div>
        </div>
      </div>
    </nav>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/projects.html.erb
<h1>Pages#projects</h1>
<p>Find me in app/views/pages/projects.html.erb</p>

<div class="row mb-5 mx-auto">
    <div class="col-md-4">
        <div class="card" style="width: 18rem;">
        <%# <img src="..." class="card-img-top" alt="..."> %>
        <%= image_tag 'cuppon.png', class:"card-img-top" %>
            <div class="card-body">
                <h5 class="card-title font-weight-bold">Proyecto Cuppon</h5>
                <p class="card-text ">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary btn-light" data-toggle="tooltip" data-placement="bottom" title="Presiona para Ver Mas.." >Ver Mas... </a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card" style="width: 18rem;">
        <%# <img src="..." class="card-img-top" alt="..."> %>
        <%= image_tag 'Ricomida.png', class:"card-img-top" %>
            <div class="card-body">
                <h5 class="card-title font-weight-bold">Proyecto Ricomida</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary btn-light"  data-toggle="tooltip" data-placement="bottom" title="Presiona para Ver Mas.." >Ver Mas... </a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card" style="width: 18rem;">
        <%# <img src="..." class="card-img-top" alt="..."> %>
        <%= image_tag 'ViajesChile.png', class:"card-img-top" %>
            <div class="card-body">
                <h5 class="card-title font-weight-bold">Proyecto Viajes Chile</h5>
                <p class="card-text" >Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary btn-light"  data-toggle="tooltip" data-placement="bottom" title="Presiona para Ver Mas.." >Ver Mas... </a>
            </div>
        </div>
    </div>
</div>